language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - tree
    - libudev-dev

script:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make V=1 || cat config.h
  - DESTDIR=/tmp/tok make install-strip
  - tree /tmp/tok
  - ldd /tmp/tok/bin/backlight
  - /tmp/tok/bin/backlight -h
